[general]

import = ["~/.config/alacritty/catppuccin-latte.toml"]

[env]

TERM = "xterm-256color"

[font]

normal = { family = "Hack Nerd Font", style = "Regular" }
size = 9

[window]

# https://alacritty.org/config-alacritty.html#s20
option_as_alt = "Both"
